"""empty message

Revision ID: 9f0428622504
Revises: ab0013adc788
Create Date: 2024-05-21 19:22:23.080563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0428622504'
down_revision = 'ab0013adc788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_ticket', schema=None) as batch_op:
        batch_op.drop_column('ticket_type')

    # ### end Alembic commands ###
